import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Source={key:string;name:string;endpoint:string;language:string;country:string;tier:number;sourceClass:string;authorityKey?:string;tierUnreviewed:boolean};
type FeedItem={externalId?:string;publishedAt?:string;title:string;url:string;excerpt?:string;isBreaking:boolean};
type FetchResult={source:Source;items:FeedItem[];error?:string};
type BatchResult={sourceKey:string;ok:boolean;status:number;inserted:number;duplicates:number;failed:number;detail?:string;failures?:unknown[]};
const SOURCES:Source[]=[
{key:"direct:khan:all",name:"경향신문",endpoint:"https://www.khan.co.kr/rss/rssdata/total_news.xml",language:"ko",country:"KR",tier:2,sourceClass:"general_news",tierUnreviewed:true},
{key:"direct:mk:all",name:"매일경제",endpoint:"https://www.mk.co.kr/rss/40300001/",language:"ko",country:"KR",tier:2,sourceClass:"financial_media",tierUnreviewed:true},
{key:"direct:donga:all",name:"동아일보",endpoint:"https://rss.donga.com/total.xml",language:"ko",country:"KR",tier:2,sourceClass:"general_news",tierUnreviewed:true},
{key:"official:fed:press",name:"Federal Reserve Board",endpoint:"https://www.federalreserve.gov/feeds/press_all.xml",language:"en",country:"US",tier:1,sourceClass:"primary_official",authorityKey:"us:federal-reserve",tierUnreviewed:false},
{key:"official:ecb:press",name:"European Central Bank",endpoint:"https://www.ecb.europa.eu/rss/press.html",language:"en",country:"EU",tier:1,sourceClass:"primary_official",authorityKey:"eu:ecb",tierUnreviewed:false},
{key:"official:bis:press",name:"Bank for International Settlements",endpoint:"https://www.bis.org/doclist/all_pressrels.rss",language:"en",country:"INT",tier:1,sourceClass:"research_institution",authorityKey:"int:bis",tierUnreviewed:false}
];
const VERSION="4.5.5-source-batch",MAX_ITEMS_PER_SOURCE=8;const USER_AGENT=`NARS-v4-shadow/${VERSION} (+https://github.com/hanul442/Black-oracle)`;const H={"content-type":"application/json; charset=utf-8"};const reply=(s:number,b:Record<string,unknown>)=>new Response(JSON.stringify(b),{status:s,headers:H});
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function decodeXml(v:string){return v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/gi,"$1").replace(/&#x([0-9a-f]+);/gi,(_,h:string)=>String.fromCodePoint(parseInt(h,16))).replace(/&#([0-9]+);/g,(_,d:string)=>String.fromCodePoint(parseInt(d,10))).replace(/&quot;/gi,'"').replace(/&apos;/gi,"'").replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&amp;/gi,"&");}
function cleanText(v:string|undefined){if(!v)return undefined;const c=decodeXml(v).replace(/<br\s*\/?>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();return c||undefined;}
function esc(v:string){return v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
function tag(block:string,names:string[]){for(const n of names){const m=block.match(new RegExp(`<${esc(n)}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${esc(n)}>`,`i`));const v=cleanText(m?.[1]);if(v)return v;}return undefined;}
function itemLink(block:string){const atom=block.match(/<link\b[^>]*\bhref\s*=\s*["']([^"']+)["'][^>]*\/?\s*>/i)?.[1],rdf=block.match(/\brdf:about\s*=\s*["']([^"']+)["']/i)?.[1],c=cleanText(atom??rdf)??tag(block,["link","guid","id"]);return c&&/^https?:\/\//i.test(c)?c:undefined;}
function blocks(xml:string,e:"item"|"entry"){const out:string[]=[];const re=new RegExp(`<${e}\\b([^>]*)>([\\s\\S]*?)<\\/${e}>`,`gi`);for(const m of xml.matchAll(re))out.push(`${m[1]??""}>${m[2]??""}`);return out;}
function toIso(v:string|undefined){if(!v)return undefined;const d=new Date(v);return isNaN(d.valueOf())?undefined:d.toISOString();}
function parseFeed(xml:string){const rss=blocks(xml,"item"),items=rss.length?rss:blocks(xml,"entry"),out:FeedItem[]=[];for(const item of items){const title=tag(item,["title","dc:title"]),url=itemLink(item);if(!title||!url)continue;out.push({externalId:tag(item,["guid","id"])??url,publishedAt:toIso(tag(item,["pubDate","published","updated","dc:date","date"])),title,url,excerpt:tag(item,["description","summary","content","content:encoded"])?.slice(0,1200),isBreaking:/^\s*\[(속보|단독)\]/u.test(title)||/\bbreaking\b/i.test(title)});if(out.length>=MAX_ITEMS_PER_SOURCE)break;}return out;}
async function fetchTimeout(url:string,ms:number,init:RequestInit={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal});}finally{clearTimeout(t);}}
function sourcePayload(s:Source){return {key:s.key,name:s.name,type:"rss",endpoint:s.endpoint,country:s.country,language:s.language,tier:s.tier,metadata:{shadow_direct:true,temporary_runner:"supabase",tier_unreviewed:s.tierUnreviewed,source_class:s.sourceClass,authority_key:s.authorityKey??null,diversified_feed:true}};}
async function expectedHash(base:string,key:string){const r=await fetchTimeout(`${base}/rest/v1/nars_system_meta?key=eq.shadow_poller_token_hash&select=value&limit=1`,4000,{headers:{authorization:`Bearer ${key}`,apikey:key}});if(!r.ok)return null;const rows=await r.json() as Array<{value?:{sha256?:string}}>;return rows[0]?.value?.sha256??null;}
async function reportFailure(base:string,key:string,s:Source,error:string){try{await fetchTimeout(`${base}/functions/v1/nars-source-status`,4000,{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({source:sourcePayload(s),ok:false,error:error.slice(0,1000)})});}catch{}}
async function fetchSource(s:Source):Promise<FetchResult>{try{const r=await fetchTimeout(s.endpoint,10000,{headers:{"user-agent":USER_AGENT,accept:"application/rss+xml, application/atom+xml, application/rdf+xml, application/xml, text/xml;q=0.9, */*;q=0.1"}});if(!r.ok)return {source:s,items:[],error:`source_http_${r.status}`};return {source:s,items:parseFeed(await r.text())};}catch(e){return {source:s,items:[],error:e instanceof Error?e.message:"source_fetch_unknown"};}}
async function ingestBatch(base:string,key:string,result:FetchResult):Promise<BatchResult>{if(result.error)return {sourceKey:result.source.key,ok:false,status:0,inserted:0,duplicates:0,failed:0,detail:result.error};const body=JSON.stringify({source:sourcePayload(result.source),documents:result.items.map(item=>({externalId:item.externalId,publishedAt:item.publishedAt,title:item.title,url:item.url,language:result.source.language,isBreaking:item.isBreaking,excerpt:item.excerpt,metadata:{feed:result.source.key,shadow_direct:true,source_class:result.source.sourceClass,authority_key:result.source.authorityKey??null}}))});for(let attempt=0;attempt<2;attempt++){try{const r=await fetchTimeout(`${base}/functions/v1/nars-ingest-batch`,12000,{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body});const text=await r.text();let data:Record<string,unknown>={};try{data=text?JSON.parse(text):{};}catch{}if(r.ok||r.status===500&&typeof data.failed==="number")return {sourceKey:result.source.key,ok:r.ok,status:r.status,inserted:Number(data.inserted??0),duplicates:Number(data.duplicates??0),failed:Number(data.failed??result.items.length),detail:typeof data.detail==="string"?data.detail:undefined,failures:Array.isArray(data.failures)?data.failures:undefined};if(!(r.status===429||r.status>=500)||attempt===1)return {sourceKey:result.source.key,ok:false,status:r.status,inserted:0,duplicates:0,failed:result.items.length,detail:text.slice(0,500)};}catch(e){if(attempt===1)return {sourceKey:result.source.key,ok:false,status:598,inserted:0,duplicates:0,failed:result.items.length,detail:e instanceof Error?e.message:"batch_timeout"};}await new Promise(resolve=>setTimeout(resolve,350));}return {sourceKey:result.source.key,ok:false,status:599,inserted:0,duplicates:0,failed:result.items.length,detail:"retry_loop_exhausted"};}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return reply(405,{ok:false,error:"method_not_allowed"});const base=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!base||!key)return reply(500,{ok:false,error:"server_not_configured"});let expected:string|null=null;try{expected=await expectedHash(base,key);}catch{}const supplied=req.headers.get("x-nars-cron-token")??"";if(!supplied||!expected||await sha256(supplied)!==expected)return reply(403,{ok:false,error:"cron_token_required"});const headers={authorization:`Bearer ${key}`,apikey:key,"content-type":"application/json"},startedAt=new Date().toISOString();let jobId:string|null=null;try{const jr=await fetchTimeout(`${base}/rest/v1/nars_job_runs`,4000,{method:"POST",headers:{...headers,prefer:"return=representation"},body:JSON.stringify({job_type:"shadow_direct_poll",job_key:`shadow-poll:${startedAt}`,status:"running",started_at:startedAt,attempt:1,items_in:0,metadata:{runner:"supabase_fallback",source_count:SOURCES.length,diversified:true,version:VERSION,batch_ingest:true}})});if(jr.ok){const j=await jr.json() as Array<{id:string}>;jobId=j[0]?.id??null;}}catch{}
const fetched=await Promise.all(SOURCES.map(fetchSource));await Promise.allSettled(fetched.filter(x=>x.error).map(x=>reportFailure(base,key,x.source,x.error!)));const batches=await Promise.all(fetched.map(x=>ingestBatch(base,key,x)));const sourceResults=fetched.map(x=>{const b=batches.find(y=>y.sourceKey===x.source.key)!;return {source:x.source.key,class:x.source.sourceClass,authority:x.source.authorityKey??null,fetchOk:!x.error,fetchError:x.error??null,items:x.items.length,batchStatus:b.status,inserted:b.inserted,duplicates:b.duplicates,ingestFailures:b.failed,firstIngestError:b.detail??(b.failures?.[0]??null)};});const fetchedItems=fetched.reduce((n,x)=>n+x.items.length,0),ingestSuccess=batches.reduce((n,b)=>n+b.inserted+b.duplicates,0),ingestFailure=batches.reduce((n,b)=>n+b.failed,0),sourceFailures=fetched.filter(x=>x.error).length,finishedAt=new Date().toISOString();if(jobId){try{await fetchTimeout(`${base}/rest/v1/nars_job_runs?id=eq.${jobId}`,4000,{method:"PATCH",headers,body:JSON.stringify({status:sourceFailures===SOURCES.length?"failed":"succeeded",finished_at:finishedAt,items_in:fetchedItems,items_out:ingestSuccess,error_count:ingestFailure+sourceFailures,metadata:{runner:"supabase_fallback",version:VERSION,diversified:true,batch_ingest:true,fetched_items:fetchedItems,ingest_success:ingestSuccess,ingest_failure:ingestFailure,source_failures:sourceFailures,sources:sourceResults}})});}catch{}}return reply(sourceFailures===SOURCES.length?503:200,{ok:sourceFailures<SOURCES.length,runner:"supabase_fallback",version:VERSION,startedAt,finishedAt,fetchedItems,ingestSuccess,ingestFailure,sourceFailures,sources:sourceResults});});
