import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Source={key:string;name:string;endpoint:string;language:string;country:string;tier:number;sourceClass:string;authorityKey?:string;tierUnreviewed:boolean};
type FeedItem={externalId?:string;publishedAt?:string;title:string;url:string;excerpt?:string;isBreaking:boolean};
type SourceResult={source:string;class:string;authority:string|null;ok:boolean;items:number;ingestSuccess:number;ingestFailures:number;error?:string};

const SOURCES:Source[]=[
 {key:"direct:khan:all",name:"경향신문",endpoint:"https://www.khan.co.kr/rss/rssdata/total_news.xml",language:"ko",country:"KR",tier:2,sourceClass:"general_news",tierUnreviewed:true},
 {key:"direct:mk:all",name:"매일경제",endpoint:"https://www.mk.co.kr/rss/40300001/",language:"ko",country:"KR",tier:2,sourceClass:"financial_media",tierUnreviewed:true},
 {key:"direct:donga:all",name:"동아일보",endpoint:"https://rss.donga.com/total.xml",language:"ko",country:"KR",tier:2,sourceClass:"general_news",tierUnreviewed:true},
 {key:"official:fed:press",name:"Federal Reserve Board",endpoint:"https://www.federalreserve.gov/feeds/press_all.xml",language:"en",country:"US",tier:1,sourceClass:"primary_official",authorityKey:"us:federal-reserve",tierUnreviewed:false},
 {key:"official:ecb:press",name:"European Central Bank",endpoint:"https://www.ecb.europa.eu/rss/press.html",language:"en",country:"EU",tier:1,sourceClass:"primary_official",authorityKey:"eu:ecb",tierUnreviewed:false},
 {key:"official:bis:press",name:"Bank for International Settlements",endpoint:"https://www.bis.org/doclist/all_pressrels.rss",language:"en",country:"INT",tier:1,sourceClass:"research_institution",authorityKey:"int:bis",tierUnreviewed:false},
];
const MAX_ITEMS=8,USER_AGENT="NARS-v4-shadow/4.5.2 (+https://github.com/hanul442/Black-oracle)";
const jsonHeaders={"content-type":"application/json; charset=utf-8"};
const reply=(status:number,body:Record<string,unknown>)=>new Response(JSON.stringify(body),{status,headers:jsonHeaders});
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function decodeXml(v:string){return v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/gi,"$1").replace(/&#x([0-9a-f]+);/gi,(_,h:string)=>String.fromCodePoint(parseInt(h,16))).replace(/&#([0-9]+);/g,(_,d:string)=>String.fromCodePoint(parseInt(d,10))).replace(/&quot;/gi,'"').replace(/&apos;/gi,"'").replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&amp;/gi,"&");}
function cleanText(v:string|undefined){if(!v)return undefined;const c=decodeXml(v).replace(/<br\s*\/?>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();return c||undefined;}
function esc(v:string){return v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
function tag(block:string,names:string[]){for(const n of names){const m=block.match(new RegExp(`<${esc(n)}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${esc(n)}>`,'i'));const v=cleanText(m?.[1]);if(v)return v;}return undefined;}
function itemLink(block:string){const a=block.match(/<link\b[^>]*\bhref\s*=\s*["']([^"']+)["'][^>]*\/?\s*>/i)?.[1];const c=cleanText(a)??tag(block,["link","guid","id"]);return c&&/^https?:\/\//i.test(c)?c:undefined;}
function blocks(xml:string,e:"item"|"entry"){const r:string[]=[];const re=new RegExp(`<${e}\\b[^>]*>([\\s\\S]*?)<\\/${e}>`,'gi');for(const m of xml.matchAll(re))r.push(m[1]);return r;}
function looksBreaking(t:string){return /^\s*\[(속보|단독)\]/u.test(t)||/\bbreaking\b/i.test(t);}
function toIso(v:string|undefined){if(!v)return undefined;const d=new Date(v);return Number.isNaN(d.valueOf())?undefined:d.toISOString();}
function parseFeed(xml:string){const rss=blocks(xml,"item"),items=rss.length?rss:blocks(xml,"entry"),out:FeedItem[]=[];for(const item of items){const title=tag(item,["title"]),url=itemLink(item);if(!title||!url)continue;out.push({externalId:tag(item,["guid","id"]),publishedAt:toIso(tag(item,["pubDate","published","updated","dc:date","date"])),title,url,excerpt:tag(item,["description","summary","content","content:encoded"])?.slice(0,1200),isBreaking:looksBreaking(title)});if(out.length>=MAX_ITEMS)break;}return out;}
async function fetchWithTimeout(url:string,ms:number){const c=new AbortController(),t=setTimeout(()=>c.abort("timeout"),ms);try{return await fetch(url,{headers:{"user-agent":USER_AGENT,accept:"application/rss+xml, application/atom+xml, application/xml, text/xml;q=0.9, */*;q=0.1"},signal:c.signal});}finally{clearTimeout(t);}}
function sourcePayload(s:Source){return{key:s.key,name:s.name,type:"rss",endpoint:s.endpoint,country:s.country,language:s.language,tier:s.tier,metadata:{shadow_direct:true,temporary_runner:"supabase",tier_unreviewed:s.tierUnreviewed,source_class:s.sourceClass,authority_key:s.authorityKey??null,diversified_feed:true}};}
async function expectedHash(base:string,key:string){const r=await fetch(`${base}/rest/v1/nars_system_meta?key=eq.shadow_poller_token_hash&select=value&limit=1`,{headers:{authorization:`Bearer ${key}`,apikey:key}});if(!r.ok)return null;const rows=await r.json() as Array<{value?:{sha256?:string}}>;return rows[0]?.value?.sha256??null;}
async function report(base:string,key:string,s:Source,ok:boolean,error?:string){try{await fetch(`${base}/functions/v1/nars-source-status`,{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({source:sourcePayload(s),ok,error:error?.slice(0,1000)})});}catch{}}
async function processSource(base:string,key:string,s:Source):Promise<SourceResult>{try{const response=await fetchWithTimeout(s.endpoint,9000);if(!response.ok)throw new Error(`source_http_${response.status}`);const items=parseFeed(await response.text());const ingest=await Promise.all(items.map(async item=>{try{const r=await fetch(`${base}/functions/v1/nars-ingest`,{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({source:sourcePayload(s),document:{externalId:item.externalId,publishedAt:item.publishedAt,title:item.title,url:item.url,language:s.language,isBreaking:item.isBreaking,excerpt:item.excerpt,metadata:{feed:s.key,shadow_direct:true,source_class:s.sourceClass,authority_key:s.authorityKey??null}}})});return r.ok;}catch{return false;}}));const success=ingest.filter(Boolean).length,fail=ingest.length-success;await report(base,key,s,true);return{source:s.key,class:s.sourceClass,authority:s.authorityKey??null,ok:true,items:items.length,ingestSuccess:success,ingestFailures:fail};}catch(e){const m=e instanceof Error?e.message:"unknown";await report(base,key,s,false,m);return{source:s.key,class:s.sourceClass,authority:s.authorityKey??null,ok:false,items:0,ingestSuccess:0,ingestFailures:0,error:m.slice(0,300)};}}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return reply(405,{ok:false,error:"method_not_allowed"});const base=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!base||!key)return reply(500,{ok:false,error:"server_not_configured"});const supplied=req.headers.get("x-nars-cron-token")??"",expected=await expectedHash(base,key);if(!supplied||!expected||await sha256(supplied)!==expected)return reply(403,{ok:false,error:"cron_token_required"});const headers={authorization:`Bearer ${key}`,apikey:key,"content-type":"application/json"},startedAt=new Date().toISOString();let jobId:string|null=null;try{const jr=await fetch(`${base}/rest/v1/nars_job_runs`,{method:"POST",headers:{...headers,prefer:"return=representation"},body:JSON.stringify({job_type:"shadow_direct_poll",job_key:`shadow-poll:${startedAt}`,status:"running",started_at:startedAt,attempt:1,items_in:0,metadata:{runner:"supabase_fallback",source_count:SOURCES.length,diversified:true,parallel:true}})});if(jr.ok){const j=await jr.json() as Array<{id:string}>;jobId=j[0]?.id??null;}}catch{}
try{const results=await Promise.all(SOURCES.map(s=>processSource(base,key,s)));const fetched=results.reduce((n,r)=>n+r.items,0),success=results.reduce((n,r)=>n+r.ingestSuccess,0),ingestFailure=results.reduce((n,r)=>n+r.ingestFailures,0),sourceFailures=results.filter(r=>!r.ok).length;const finishedAt=new Date().toISOString();if(jobId){await fetch(`${base}/rest/v1/nars_job_runs?id=eq.${jobId}`,{method:"PATCH",headers,body:JSON.stringify({status:sourceFailures===SOURCES.length?"failed":"succeeded",finished_at:finishedAt,items_in:fetched,items_out:success,error_count:ingestFailure+sourceFailures,metadata:{runner:"supabase_fallback",diversified:true,parallel:true,fetched_items:fetched,ingest_success:success,ingest_failure:ingestFailure,source_failures:sourceFailures,sources:results}})}).catch(()=>undefined);}return reply(sourceFailures===SOURCES.length?503:200,{ok:sourceFailures<SOURCES.length,runner:"supabase_fallback",version:"4.5.2-source-diversification",startedAt,finishedAt,fetchedItems:fetched,ingestSuccess:success,ingestFailure,sourceFailures,sources:results});}catch(e){const message=e instanceof Error?e.message:"unknown_fatal";if(jobId){await fetch(`${base}/rest/v1/nars_job_runs?id=eq.${jobId}`,{method:"PATCH",headers,body:JSON.stringify({status:"failed",finished_at:new Date().toISOString(),error_count:1,metadata:{runner:"supabase_fallback",diversified:true,parallel:true,fatal_error:message.slice(0,500)}})}).catch(()=>undefined);}return reply(500,{ok:false,error:"shadow_poll_failed",detail:message.slice(0,300)});}});