import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type SourceType="rss"|"api"|"filing"|"government"|"research"|"newsletter"|"social"|"other";
type Source={key:string;name:string;type:SourceType;endpoint?:string;country?:string;language?:string;tier?:number;metadata?:Record<string,unknown>};
type DocumentInput={externalId?:string;publishedAt?:string;title:string;url:string;language?:string;isBreaking?:boolean;excerpt?:string;contentHash?:string;metadata?:Record<string,unknown>};
type Payload={source:Source;documents:DocumentInput[]};
const VERSION="4.5.4-batch-ingest";
const SOURCE_TYPES=new Set<SourceType>(["rss","api","filing","government","research","newsletter","social","other"]);
const headersJson={"content-type":"application/json; charset=utf-8"};
const reply=(status:number,body:Record<string,unknown>)=>new Response(JSON.stringify(body),{status,headers:headersJson});

function normalizeTitle(v:string){return v.normalize("NFKC").toLowerCase().replace(/^\s*\[(속보|종합|단독|영상|알림)\]\s*/u,"").replace(/\s+/g," ").trim();}
function canonicalizeUrl(raw:string){const u=new URL(raw);if(!/^https?:$/.test(u.protocol))throw new Error("unsupported_url_protocol");u.hash="";for(const k of ["utm_source","utm_medium","utm_campaign","utm_term","utm_content","fbclid","gclid","traffic_source"])u.searchParams.delete(k);u.searchParams.sort();if(u.pathname.length>1)u.pathname=u.pathname.replace(/\/+$/,"");return u.toString();}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function valid(payload:unknown):payload is Payload{if(!payload||typeof payload!=="object")return false;const p=payload as Partial<Payload>;if(!p.source||typeof p.source.key!=="string"||!p.source.key.trim()||typeof p.source.name!=="string"||!p.source.name.trim()||typeof p.source.type!=="string"||!SOURCE_TYPES.has(p.source.type as SourceType)||!Array.isArray(p.documents)||p.documents.length<1||p.documents.length>50)return false;return p.documents.every(d=>d&&typeof d.title==="string"&&d.title.trim()&&typeof d.url==="string"&&d.url.trim());}

async function lookup(base:string,headers:Record<string,string>,sourceId:string,externalId:string|undefined,dedupKey:string){if(externalId){const r=await fetch(`${base}/rest/v1/nars_documents?source_id=eq.${sourceId}&external_id=eq.${encodeURIComponent(externalId)}&select=id&limit=1`,{headers});if(!r.ok)throw new Error(`external_lookup_${r.status}:${await r.text()}`);const rows=await r.json() as Array<{id:string}>;if(rows[0]?.id)return rows[0].id;}const r=await fetch(`${base}/rest/v1/nars_documents?dedup_key=eq.${encodeURIComponent(dedupKey)}&select=id&limit=1`,{headers});if(!r.ok)throw new Error(`dedup_lookup_${r.status}:${await r.text()}`);const rows=await r.json() as Array<{id:string}>;return rows[0]?.id??null;}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return reply(405,{ok:false,error:"method_not_allowed"});const base=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!base||!key)return reply(500,{ok:false,error:"server_not_configured"});const bearer=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??"";if(bearer!==key)return reply(403,{ok:false,error:"service_role_required"});let raw:unknown;try{raw=await req.json();}catch{return reply(400,{ok:false,error:"invalid_json"});}if(!valid(raw))return reply(400,{ok:false,error:"invalid_payload"});const payload=raw;const headers={authorization:`Bearer ${key}`,apikey:key,"content-type":"application/json"};const seenAt=new Date().toISOString();let sourceId:string|null=null;
try{const sr=await fetch(`${base}/rest/v1/nars_sources?on_conflict=source_key`,{method:"POST",headers:{...headers,prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({source_key:payload.source.key.trim(),name:payload.source.name.trim(),source_type:payload.source.type,endpoint:payload.source.endpoint??null,country:payload.source.country??null,language:payload.source.language??null,tier:Math.min(5,Math.max(0,payload.source.tier??2)),enabled:true,metadata:payload.source.metadata??{},updated_at:seenAt})});if(!sr.ok)throw new Error(`source_upsert_${sr.status}:${await sr.text()}`);const rows=await sr.json() as Array<{id:string}>;sourceId=rows[0]?.id??null;if(!sourceId)throw new Error("source_upsert_returned_no_id");
let inserted=0,duplicates=0,failed=0;const failures:Array<{index:number;error:string}>=[];
for(let i=0;i<payload.documents.length;i++){const doc=payload.documents[i];try{const canonicalUrl=canonicalizeUrl(doc.url),normalizedTitle=normalizeTitle(doc.title),dedupKey=await sha256(`${canonicalUrl}\n${normalizedTitle}`),externalId=doc.externalId?.trim()||undefined;let documentId=await lookup(base,headers,sourceId,externalId,dedupKey),wasInserted=false;if(!documentId){const ir=await fetch(`${base}/rest/v1/nars_documents?on_conflict=dedup_key`,{method:"POST",headers:{...headers,prefer:"resolution=ignore-duplicates,return=representation"},body:JSON.stringify({source_id:sourceId,external_id:externalId??null,published_at:doc.publishedAt??null,retrieved_at:seenAt,title:doc.title.trim(),canonical_url:canonicalUrl,normalized_title:normalizedTitle,dedup_key:dedupKey,language:doc.language??payload.source.language??null,is_breaking:doc.isBreaking??false,excerpt:doc.excerpt??null,content_hash:doc.contentHash??null,raw_metadata:doc.metadata??{},ingest_version:VERSION,ingest_origin:"collector"})});if(ir.ok){const docs=await ir.json() as Array<{id:string}>;documentId=docs[0]?.id??null;wasInserted=Boolean(documentId);}else if(ir.status!==409)throw new Error(`document_insert_${ir.status}:${await ir.text()}`);if(!documentId)documentId=await lookup(base,headers,sourceId,externalId,dedupKey);}if(!documentId)throw new Error("document_id_not_resolved");const sight=await fetch(`${base}/rest/v1/rpc/nars_record_sighting`,{method:"POST",headers,body:JSON.stringify({p_document_id:documentId,p_origin:"collector",p_seen_at:seenAt,p_legacy_ref:null,p_metadata:{ingest_version:VERSION,source_key:payload.source.key.trim(),batch:true}})});if(!sight.ok)throw new Error(`sighting_${sight.status}:${await sight.text()}`);if(wasInserted)inserted++;else duplicates++;}catch(e){failed++;failures.push({index:i,error:(e instanceof Error?e.message:"unknown").slice(0,500)});}}
await fetch(`${base}/rest/v1/nars_sources?id=eq.${sourceId}`,{method:"PATCH",headers,body:JSON.stringify({health_status:failed===payload.documents.length?"degraded":"up",last_success_at:failed===payload.documents.length?undefined:seenAt,last_failure_at:failed?seenAt:undefined,consecutive_failures:failed===payload.documents.length?1:0,updated_at:seenAt})}).catch(()=>{});
return reply(failed===payload.documents.length?500:200,{ok:failed<payload.documents.length,version:VERSION,sourceId,total:payload.documents.length,inserted,duplicates,failed,failures:failures.slice(0,5)});
}catch(e){const message=(e instanceof Error?e.message:"unknown").slice(0,1500);return reply(500,{ok:false,error:"batch_ingest_failed",version:VERSION,detail:message,sourceId});}});
