import assert from 'node:assert/strict';
import test from 'node:test';
import { REQUIRED_VALIDATION_STAGES, type ValidationStage } from './validationExperiment';
import type { ValidationEvaluation } from './validationStageResult';
import { bindStrategyCandidateToValidation } from './strategyValidationBinding';
import { routeChampionChallenger } from './championChallengerRouter';
import { arbitrateGovernance } from './governanceArbiter';
import { evaluateBotRiskExecutionBoundary } from '../../server/trading/botRiskExecutionBoundary';
import { buildUpbitOrderDryRun, reconcileUpbitDryRun } from './upbitDryRunReconciliation';
import { evaluateLiveCanaryReadiness } from './liveCanaryReadiness';
import { attributeObservedOutcome } from './outcomeAttribution';
const T='2026-09-22T00:00:30.000Z',OBSERVED='2026-09-22T00:00:20.000Z',EXPIRES='2026-09-22T00:01:30.000Z';
function evaluation(experimentId:string):ValidationEvaluation{const fingerprints=Object.fromEntries(REQUIRED_VALIDATION_STAGES.map(s=>[s,`sha256:${experimentId}:${s}`])) as Record<ValidationStage,string>;return{schema:'bot.validation-evaluation.v1',experimentId,evaluatedAt:OBSERVED,status:'PASS',stageResultFingerprints:fingerprints,gates:[{gateId:'s13',status:'PASS',reason:'deterministic fixture'}],promotionAuthority:false,executionAuthority:false,capitalAuthority:false};}
function governedPaperFixture(options:{killSwitch?:boolean;staleGovernance?:boolean;councilReject?:boolean}={}){const champion=bindStrategyCandidateToValidation({strategyId:'alpha-champion',strategyRevision:'r13',experimentId:'exp-s13-champion',evaluation:evaluation('exp-s13-champion')});const challenger=bindStrategyCandidateToValidation({strategyId:'alpha-challenger',strategyRevision:'r13',experimentId:'exp-s13-challenger',evaluation:evaluation('exp-s13-challenger')});const router=routeChampionChallenger({champion:{role:'CHAMPION',binding:champion,comparisonScore:2,observedAt:OBSERVED,maxAgeMs:60000,regimeFit:true},challenger:{role:'CHALLENGER',binding:challenger,comparisonScore:1,observedAt:OBSERVED,maxAgeMs:60000,regimeFit:true},evaluatedAt:T});const findingTime=options.staleGovernance?'2026-09-21T23:00:00.000Z':OBSERVED;const governance=arbitrateGovernance({routerDecision:router,council:{sourceId:'council-s13',strategyId:'alpha-champion',strategyRevision:'r13',observedAt:findingTime,maxAgeMs:60000,verdict:options.councilReject?'REJECT':'APPROVE',evidenceFingerprints:['ev:council:s13']},redTeam:{sourceId:'redteam-s13',strategyId:'alpha-champion',strategyRevision:'r13',observedAt:findingTime,maxAgeMs:60000,verdict:'CLEAR',evidenceFingerprints:['ev:redteam:s13']},evaluatedAt:T});const risk=evaluateBotRiskExecutionBoundary({contractVersion:'bot.risk-execution-boundary.v1',now:T,mode:'PAPER',governance:{contractVersion:'bot.governance-decision.v1',decisionId:'gov-s13',outcome:governance.action,strategyId:governance.strategyId??undefined,strategyRevision:governance.strategyRevision??undefined,evidenceFingerprint:`gov:${governance.reason}:s13`,decidedAt:governance.evaluatedAt,executionAuthority:false,capitalAuthority:false,riskBypassAuthority:false,liveAuthority:false},orderIntent:governance.action==='APPROVE'?{contractVersion:'bot.canonical-order-intent.v1',intentId:'intent-s13',market:'KRW-BTC',side:'BUY',quantity:0.001,referencePrice:100000000,strategyId:'alpha-champion',strategyRevision:'r13',observedAt:OBSERVED,maxAgeMs:60000}:undefined,risk:governance.action==='APPROVE'?{snapshotId:'risk-s13',strategyId:'alpha-champion',strategyRevision:'r13',observedAt:OBSERVED,maxAgeMs:60000,killSwitchEngaged:options.killSwitch??false,duplicateIntent:false,marketDataFresh:true,limitsSatisfied:true}:undefined});return{champion,challenger,router,governance,risk};}
function fullPaperChain(){const upstream=governedPaperFixture();const dryRun=buildUpbitOrderDryRun({adapter:'UPBIT',operation:'ORDER_DRY_RUN',risk:{risk:upstream.risk,routerDecisionId:'router-s13',eventLedgerId:'event-ledger-s13',decisionReplayId:'decision-replay-s13',killSwitchActive:false},idempotencyKey:'idem-s13',requestedAt:T});const reconciliation=reconcileUpbitDryRun(dryRun,dryRun);const readiness=evaluateLiveCanaryReadiness({mode:'PAPER',evaluatedAt:T,killSwitchActive:false,adapterHealth:{adapter:'UPBIT',status:'HEALTHY',observedAt:OBSERVED,expiresAt:EXPIRES},reconciliation,expectedRequestId:dryRun.requestId,expectedIdempotencyKey:dryRun.idempotencyKey,expectedEventLedgerId:dryRun.lineage.eventLedgerId,expectedDecisionReplayId:dryRun.lineage.decisionReplayId});const attribution=attributeObservedOutcome({evaluatedAt:T,maxOutcomeAgeMs:60000,dryRun,readiness,outcome:{outcomeId:'outcome-s13',mode:'PAPER',market:'KRW-BTC',observedAt:T,sourceEventLedgerId:dryRun.lineage.eventLedgerId,sourceDecisionReplayId:dryRun.lineage.decisionReplayId,requestId:dryRun.requestId,idempotencyKey:dryRun.idempotencyKey,realizedPnl:1000,realizedReturn:0.01}});return{...upstream,dryRun,reconciliation,readiness,attribution};}
test('S14 deterministic PAPER fixture preserves Risk-attested economics, lineage and zero financial authority',()=>{const c=fullPaperChain();assert.equal(c.risk.outcome,'ALLOW_INTENT');assert.equal(c.dryRun.status,'DRY_RUN');assert.equal(c.dryRun.market,c.risk.orderIntent?.market);assert.equal(c.dryRun.quantity,c.risk.orderIntent?.quantity);assert.equal(c.dryRun.lineage.orderIntentFingerprint,c.risk.orderIntent?.fingerprint);assert.equal(c.reconciliation.status,'MATCH');assert.equal(c.readiness.status,'READY');assert.equal(c.attribution.status,'ATTRIBUTED');for(const b of[c.router,c.governance,c.risk,c.dryRun,c.readiness,c.attribution]){assert.equal(b.executionAuthority,false);assert.equal(b.capitalAuthority,false);assert.equal(b.liveAuthority,false);}});
test('stale governance evidence and Council rejection terminate before Risk',()=>{for(const f of[governedPaperFixture({staleGovernance:true}),governedPaperFixture({councilReject:true})]){assert.equal(f.governance.action,'NO_TRADE');assert.equal(f.risk.outcome,'NO_TRADE');assert.deepEqual(f.risk.reasonCodes,['GOVERNANCE_NO_TRADE']);}});
test('kill switch terminates at Risk',()=>{const f=governedPaperFixture({killSwitch:true});assert.equal(f.risk.outcome,'NO_TRADE');assert.deepEqual(f.risk.reasonCodes,['KILL_SWITCH_ENGAGED']);});
test('reconciliation mismatch fails readiness closed',()=>{const c=fullPaperChain();const observed={...c.dryRun,referencePrice:c.dryRun.referencePrice+1};const reconciliation=reconcileUpbitDryRun(c.dryRun,observed);const readiness=evaluateLiveCanaryReadiness({mode:'PAPER',evaluatedAt:T,killSwitchActive:false,adapterHealth:{adapter:'UPBIT',status:'HEALTHY',observedAt:OBSERVED,expiresAt:EXPIRES},reconciliation,expectedRequestId:c.dryRun.requestId,expectedIdempotencyKey:c.dryRun.idempotencyKey,expectedEventLedgerId:c.dryRun.lineage.eventLedgerId,expectedDecisionReplayId:c.dryRun.lineage.decisionReplayId});assert.equal(reconciliation.status,'NO_TRADE');assert.equal(readiness.status,'NO_TRADE');});
test('outcome lineage mismatch is terminal',()=>{const c=fullPaperChain();const a=attributeObservedOutcome({evaluatedAt:T,maxOutcomeAgeMs:60000,dryRun:c.dryRun,readiness:c.readiness,outcome:{outcomeId:'outcome-mismatch',mode:'PAPER',market:'KRW-BTC',observedAt:T,sourceEventLedgerId:'wrong-ledger',sourceDecisionReplayId:c.dryRun.lineage.decisionReplayId,requestId:c.dryRun.requestId,idempotencyKey:c.dryRun.idempotencyKey,realizedPnl:99,realizedReturn:0.99}});assert.equal(a.status,'NO_TRADE');assert.equal(a.reason,'LINEAGE_MISMATCH');assert.equal(a.realizedPnl,null);});
