import { strict as assert } from 'node:assert';
import { evaluateBotRiskExecutionBoundary } from '../../server/trading/botRiskExecutionBoundary';
import { buildUpbitOrderDryRun, reconcileUpbitDryRun, type UpbitDryRunRequest } from './upbitDryRunReconciliation';
function riskDecision(){return evaluateBotRiskExecutionBoundary({contractVersion:'bot.risk-execution-boundary.v1',now:'2026-09-21T15:09:30.000Z',mode:'LIVE_SHADOW',governance:{contractVersion:'bot.governance-decision.v1',decisionId:'gov-1',outcome:'APPROVE',strategyId:'strategy-1',strategyRevision:'r1',evidenceFingerprint:'gov-fp',decidedAt:'2026-09-21T15:09:00.000Z',executionAuthority:false,capitalAuthority:false,riskBypassAuthority:false,liveAuthority:false},orderIntent:{contractVersion:'bot.canonical-order-intent.v1',intentId:'intent-1',market:'KRW-BTC',side:'BUY',quantity:0.001,referencePrice:100000000,strategyId:'strategy-1',strategyRevision:'r1',observedAt:'2026-09-21T15:09:10.000Z',maxAgeMs:120000},risk:{snapshotId:'risk-snapshot-1',strategyId:'strategy-1',strategyRevision:'r1',observedAt:'2026-09-21T15:09:20.000Z',maxAgeMs:60000,killSwitchEngaged:false,duplicateIntent:false,marketDataFresh:true,limitsSatisfied:true}})}
const base=():UpbitDryRunRequest=>({adapter:'UPBIT',operation:'ORDER_DRY_RUN',idempotencyKey:'idem-1',requestedAt:'2026-09-21T15:10:00.000Z',risk:{risk:riskDecision(),routerDecisionId:'router-1',eventLedgerId:'event-1',decisionReplayId:'replay-1',killSwitchActive:false}});
{const p=buildUpbitOrderDryRun(base());assert.equal(p.status,'DRY_RUN');assert.equal(p.submissionAuthority,false);assert.equal(p.executionAuthority,false);assert.equal(p.liveAuthority,false);assert.equal(p.notional,100000);assert.equal(p.lineage.orderIntentFingerprint,riskDecision().orderIntent?.fingerprint);assert.equal(reconcileUpbitDryRun(p,p).status,'MATCH');}
{const r=base();r.risk.risk={...r.risk.risk,outcome:'NO_TRADE',orderIntent:undefined};assert.equal(buildUpbitOrderDryRun(r).reason,'RISK_NO_TRADE_TERMINAL');}
{const r=base();r.risk.killSwitchActive=true;assert.equal(buildUpbitOrderDryRun(r).reason,'KILL_SWITCH_ACTIVE');}
{const r=base();r.requestedAt='2026-09-21T15:12:00.000Z';assert.equal(buildUpbitOrderDryRun(r).reason,'STALE_OR_FUTURE_RISK');}
{const r=base();assert.equal(buildUpbitOrderDryRun(r,new Set(['idem-1'])).reason,'IDEMPOTENCY_CONFLICT');}
{const p=buildUpbitOrderDryRun(base());const m={...p,quantity:p.quantity+1};assert.equal(reconcileUpbitDryRun(p,m).status,'NO_TRADE');}
console.log('upbitDryRunReconciliation tests passed');
