import type { BotRiskExecutionDecision } from '../../server/trading/botRiskExecutionBoundary';
export const UPBIT_DRY_RUN_CONTRACT_VERSION = 'bot.upbit-dry-run-reconciliation.v1' as const;
export type AlphaExecutionMode = 'PAPER' | 'LIVE_SHADOW'; export type OrderSide = 'BUY' | 'SELL';
export interface RiskApprovedIntent { contractVersion: 'bot.risk-execution-boundary.v1'; decision: 'APPROVE' | 'NO_TRADE'; mode: AlphaExecutionMode; intentId: string; market: string; side: OrderSide; quantity: number; referencePrice: number; evaluatedAt: string; expiresAt: string; strategyId: string; routerDecisionId: string; governanceDecisionId: string; riskDecisionId: string; eventLedgerId: string; decisionReplayId: string; killSwitchActive: boolean; executionAuthority: false; capitalAuthority: false; liveAuthority: false; }
export interface RiskAttestedDryRunLineage { risk: BotRiskExecutionDecision; routerDecisionId: string; eventLedgerId: string; decisionReplayId: string; killSwitchActive: boolean; }
export interface UpbitDryRunRequest { adapter: 'UPBIT'; operation: 'ORDER_DRY_RUN'; risk: RiskAttestedDryRunLineage; idempotencyKey: string; requestedAt: string; }
export interface UpbitDryRunPreview { contractVersion: typeof UPBIT_DRY_RUN_CONTRACT_VERSION; status: 'DRY_RUN' | 'NO_TRADE'; reason: string; requestId: string; idempotencyKey: string; mode: AlphaExecutionMode; market: string; side: OrderSide; quantity: number; referencePrice: number; notional: number; lineage: { intentId: string; strategyId: string; routerDecisionId: string; governanceDecisionId: string; riskDecisionId: string; eventLedgerId: string; decisionReplayId: string; orderIntentFingerprint: string; }; submissionAuthority: false; executionAuthority: false; capitalAuthority: false; liveAuthority: false; }
export interface ReconciliationResult { contractVersion: typeof UPBIT_DRY_RUN_CONTRACT_VERSION; status: 'MATCH' | 'NO_TRADE'; reason: string; requestId: string; idempotencyKey: string; eventLedgerId: string; decisionReplayId: string; executionAuthority: false; liveAuthority: false; }
const isoMs=(v:string)=>Date.parse(v); function stableId(parts:string[]){let h=2166136261;for(const ch of parts.join('|')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return `upbit-dry-v1-${(h>>>0).toString(16).padStart(8,'0')}`}
function noTrade(request:UpbitDryRunRequest,reason:string):UpbitDryRunPreview { const d=request.risk.risk, o=d.orderIntent; return {contractVersion:UPBIT_DRY_RUN_CONTRACT_VERSION,status:'NO_TRADE',reason,requestId:stableId([request.idempotencyKey,d.decisionId]),idempotencyKey:request.idempotencyKey,mode:d.mode,market:o?.market??'',side:o?.side??'BUY',quantity:0,referencePrice:0,notional:0,lineage:{intentId:o?.intentId??'',strategyId:d.strategyId??'',routerDecisionId:request.risk.routerDecisionId,governanceDecisionId:d.governanceDecisionId,riskDecisionId:d.decisionId,eventLedgerId:request.risk.eventLedgerId,decisionReplayId:request.risk.decisionReplayId,orderIntentFingerprint:o?.fingerprint??''},submissionAuthority:false,executionAuthority:false,capitalAuthority:false,liveAuthority:false}; }
export function buildUpbitOrderDryRun(request:UpbitDryRunRequest,seenIdempotencyKeys:ReadonlySet<string>=new Set()):UpbitDryRunPreview { const d=request.risk.risk,o=d.orderIntent,requestedAt=isoMs(request.requestedAt); if(d.contractVersion!=='bot.risk-execution-boundary.v1'||d.outcome!=='ALLOW_INTENT'||!o)return noTrade(request,'RISK_NO_TRADE_TERMINAL'); if(d.mode!=='PAPER'&&d.mode!=='LIVE_SHADOW')return noTrade(request,'UNSUPPORTED_EXECUTION_MODE'); if(request.risk.killSwitchActive)return noTrade(request,'KILL_SWITCH_ACTIVE'); if(!request.idempotencyKey||seenIdempotencyKeys.has(request.idempotencyKey))return noTrade(request,'IDEMPOTENCY_CONFLICT'); const evaluatedAt=isoMs(d.evaluatedAt),expiresAt=isoMs(o.expiresAt); if(![requestedAt,evaluatedAt,expiresAt].every(Number.isFinite)||evaluatedAt>requestedAt||expiresAt<requestedAt)return noTrade(request,'STALE_OR_FUTURE_RISK'); if(![o.intentId,o.market,o.strategyId,d.governanceDecisionId,d.decisionId,request.risk.routerDecisionId,request.risk.eventLedgerId,request.risk.decisionReplayId,o.fingerprint].every(Boolean))return noTrade(request,'MISSING_LINEAGE'); if(o.strategyId!==d.strategyId||o.strategyRevision!==d.strategyRevision)return noTrade(request,'RISK_ATTESTATION_IDENTITY_MISMATCH'); const requestId=stableId([request.idempotencyKey,o.fingerprint,d.decisionId]); return {contractVersion:UPBIT_DRY_RUN_CONTRACT_VERSION,status:'DRY_RUN',reason:'RISK_ATTESTED_DRY_RUN_ONLY',requestId,idempotencyKey:request.idempotencyKey,mode:d.mode,market:o.market,side:o.side,quantity:o.quantity,referencePrice:o.referencePrice,notional:o.quantity*o.referencePrice,lineage:{intentId:o.intentId,strategyId:o.strategyId,routerDecisionId:request.risk.routerDecisionId,governanceDecisionId:d.governanceDecisionId,riskDecisionId:d.decisionId,eventLedgerId:request.risk.eventLedgerId,decisionReplayId:request.risk.decisionReplayId,orderIntentFingerprint:o.fingerprint},submissionAuthority:false,executionAuthority:false,capitalAuthority:false,liveAuthority:false}; }
export function reconcileUpbitDryRun(expected:UpbitDryRunPreview,observed:UpbitDryRunPreview):ReconciliationResult { const match=expected.status==='DRY_RUN'&&observed.status==='DRY_RUN'&&expected.requestId===observed.requestId&&expected.idempotencyKey===observed.idempotencyKey&&expected.mode===observed.mode&&expected.market===observed.market&&expected.side===observed.side&&expected.quantity===observed.quantity&&expected.referencePrice===observed.referencePrice&&expected.notional===observed.notional&&JSON.stringify(expected.lineage)===JSON.stringify(observed.lineage); return {contractVersion:UPBIT_DRY_RUN_CONTRACT_VERSION,status:match?'MATCH':'NO_TRADE',reason:match?'DETERMINISTIC_RECONCILIATION_MATCH':'RECONCILIATION_MISMATCH',requestId:expected.requestId,idempotencyKey:expected.idempotencyKey,eventLedgerId:expected.lineage.eventLedgerId,decisionReplayId:expected.lineage.decisionReplayId,executionAuthority:false,liveAuthority:false}; }
