import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, Bot, Database, GripVertical, RefreshCw, ShieldCheck, TrendingUp, WalletCards, X } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useAppContext } from '../store';

type CouncilMember = { role: string; vote: string; confidence: number; reasons: string[] };
type Council = { mode: string; executionAuthority: boolean; verdict: string; approveCount: number; cautionCount: number; rejectCount: number; abstainCount: number; members: CouncilMember[]; summary: string };
type Decision = {
  timestamp: number; market: string; decision: string; regime?: string | null; regimeConfidence?: number | null; oracleTradeScore?: number | null; confidence?: number | null;
  strategyDisposition?: string | null; riskDisposition?: string | null; riskReasons?: string[]; evidenceActiveCount?: number; evidenceIds?: string[]; primaryReason?: string | null; reasons?: string[];
  council?: Council | null; router?: any; forecast?: any; technicalEvidence?: any; structure?: any; microstructure?: any; tradeMap?: any; preRiskContext?: any;
};
type Position = { market: string; quantity: number; entryPrice: number; markPrice: number; marketValue: number; unrealizedPnl: number; stopLossPrice?: number | null; takeProfit1Price?: number | null; takeProfit2Price?: number | null; takeProfit1Taken?: boolean; protectionRevision?: number; openedAt: number };
type Trade = { id: string; market: string; closedAt: number; netPnl: number; returnPct: number; exitReason?: string; strategyVersion?: string | null };
type Evidence = { id: string; market: string; title: string; direction: string; source_type?: string; source?: string | null; evidence_grade?: string | null; evidence_score?: number | null; eligible_for_new_risk?: boolean; observed_at: string; rationale?: string };
type StatusPayload = {
  success?: boolean; available?: boolean; status?: string; now?: number; mode?: string; strategyVersion?: string | null;
  checkpoint?: { savedAt?: number; reason?: string; runtimeId?: string; backend?: string };
  loop?: { cycleCount?: number; ageMs?: number | null; stale?: boolean; lastCycle?: { scanned?: number; entered?: number; exited?: number; held?: number; noTrade?: number; errors?: any[]; evidenceOps?: any; equityCycle?: any } | null };
  portfolio?: { initialEquity?: number; equity?: number; cash?: number; realizedPnl?: number; feesPaid?: number; dailyPnlPct?: number; currentDrawdownPct?: number; openPositions?: Position[] };
  ingestion?: { evidenceActive?: number; externalEvidenceActive?: number; evidenceRequests?: number; narsInboxRecent?: number; lastCycleErrors?: number };
  council?: { mode?: string; executionAuthority?: boolean; latest?: Council | null; stats?: { reviewed: number; approve: number; conditional: number; reject: number } };
  evidenceFlow?: Evidence[]; decisionTape?: Decision[]; recentTrades?: Trade[]; equityCurve?: Array<{ timestamp: number; equity: number }>;
};

const fmtKrw = (value: number | null | undefined) => new Intl.NumberFormat('ko-KR', { maximumFractionDigits: 0 }).format(Number(value ?? 0));
const pct = (value: number | null | undefined, digits = 2) => `${(Number(value ?? 0) * 100).toFixed(digits)}%`;
const ago = (timestamp?: number | null) => { if (!timestamp) return '—'; const seconds = Math.max(0, Math.floor((Date.now() - timestamp) / 1000)); if (seconds < 60) return `${seconds}s`; if (seconds < 3600) return `${Math.floor(seconds / 60)}m`; return `${Math.floor(seconds / 3600)}h`; };
const tone = (value?: string | null) => { const normalized = String(value || '').toUpperCase(); if (['OK', 'PASS', 'PASSED', 'APPROVE', 'ENTER', 'BULLISH', 'ACTIVE', 'HEALTHY'].includes(normalized)) return 'text-[#77B9A5]'; if (['REJECT', 'BLOCKED', 'ERROR', 'BEARISH', 'EXIT', 'DEGRADED'].includes(normalized)) return 'text-[#D07D7D]'; if (['CONDITIONAL', 'CAUTION', 'WAIT', 'NO_TRADE', 'THROTTLED', 'EMPTY', 'QUIET'].includes(normalized)) return 'text-[#C7AA71]'; return 'text-[#9AA5AE]'; };
const Card = ({ children, className = '' }: React.PropsWithChildren<{ className?: string }>) => <section className={`border border-white/[0.07] bg-[#070B10] ${className}`}>{children}</section>;
const Kicker = ({ children }: React.PropsWithChildren) => <div className="font-mono text-[7px] uppercase tracking-[0.18em] text-[#58636D]">{children}</div>;
const Metric = ({ label, value, valueClass = 'text-[#E1E6E9]' }: { label: string; value: string; valueClass?: string }) => <div className="bg-[#070B10] p-3.5"><Kicker>{label}</Kicker><div className={`mt-2 font-mono text-[12px] ${valueClass}`}>{value}</div></div>;
const Progress = ({ value }: { value: number }) => <div className="mt-2 h-1.5 overflow-hidden bg-white/[0.05]"><div className="h-full bg-[#43D9E6]" style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>;

export const CommandCenterView: React.FC = () => {
  const { setCurrentView } = useAppContext() as any;
  const [payload, setPayload] = useState<StatusPayload | null>(null);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<Decision | null>(null);
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const dragRef = useRef({ active: false, y: 0, top: 0 });

  const load = async () => { try { const response = await fetch('/api/trading-status', { cache: 'no-store' }); setPayload(await response.json() as StatusPayload); } catch { setPayload(null); } finally { setLoading(false); } };
  useEffect(() => { void load(); const interval = window.setInterval(() => void load(), 30_000); const onVisible = () => document.visibilityState === 'visible' && void load(); document.addEventListener('visibilitychange', onVisible); window.addEventListener('online', load); return () => { window.clearInterval(interval); document.removeEventListener('visibilitychange', onVisible); window.removeEventListener('online', load); }; }, []);

  const positions = payload?.portfolio?.openPositions ?? [];
  const decisions = payload?.decisionTape ?? [];
  const evidence = payload?.evidenceFlow ?? [];
  const trades = payload?.recentTrades ?? [];
  const equityCurve = payload?.equityCurve ?? [];
  const latestCouncil = payload?.council?.latest ?? decisions.find((item) => item.council)?.council ?? null;
  const latestDecision = decisions[0] ?? null;
  const totalUnrealized = useMemo(() => positions.reduce((sum, item) => sum + Number(item.unrealizedPnl || 0), 0), [positions]);
  const rejectedCandidates = useMemo(() => decisions.filter((item) => item.riskDisposition === 'REJECT').sort((a, b) => Number(b.oracleTradeScore ?? 0) - Number(a.oracleTradeScore ?? 0)), [decisions]);
  const approvedCandidates = useMemo(() => decisions.filter((item) => item.riskDisposition === 'APPROVE').sort((a, b) => Number(b.oracleTradeScore ?? 0) - Number(a.oracleTradeScore ?? 0)), [decisions]);
  const safetyDecision = rejectedCandidates[0] ?? approvedCandidates[0] ?? null;
  const safetyState = rejectedCandidates.length ? 'BLOCKED' : approvedCandidates.length ? 'PASSED' : 'IDLE';
  const dailyLoss = Math.max(0, -Number(payload?.portfolio?.dailyPnlPct ?? 0));
  const drawdown = Math.max(0, Number(payload?.portfolio?.currentDrawdownPct ?? 0));
  const evidenceAttached = decisions.reduce((max, item) => Math.max(max, Number(item.evidenceActiveCount ?? 0)), 0);
  const evidenceChart = [
    { name: 'NARS recent', value: Number(payload?.ingestion?.narsInboxRecent ?? 0) },
    { name: 'Eligible now', value: Number(payload?.ingestion?.externalEvidenceActive ?? 0) },
    { name: 'Attached', value: evidenceAttached },
  ];
  const equityData = equityCurve.map((point) => ({ ...point, time: new Date(point.timestamp).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' }) }));
  const initialEquity = Number(payload?.portfolio?.initialEquity ?? 0);
  const initialIs100m = initialEquity === 100_000_000;

  const statusCells = [
    { label: 'Runtime', value: payload?.status || 'UNKNOWN', sub: payload?.checkpoint?.runtimeId || 'no checkpoint' },
    { label: 'NARS', value: (payload?.ingestion?.narsInboxRecent ?? 0) > 0 ? 'FLOWING' : 'QUIET', sub: `${payload?.ingestion?.narsInboxRecent ?? 0} recent packets` },
    { label: 'Evidence', value: `${payload?.ingestion?.externalEvidenceActive ?? 0} ELIGIBLE`, sub: 'current evidence · not positions' },
    { label: 'Council', value: latestCouncil?.verdict || 'NOT OBSERVED', sub: `${payload?.council?.mode || 'SHADOW'} · no execution authority` },
    { label: 'Strategy', value: latestDecision?.strategyDisposition || payload?.strategyVersion || '—', sub: latestDecision?.market || 'no recent decision' },
    { label: 'New Entry Safety', value: safetyState, sub: safetyDecision ? `${safetyDecision.market} · score ${safetyDecision.oracleTradeScore ?? '—'}` : 'no entry candidate evaluated' },
    { label: 'Paper Capital', value: initialIs100m ? '₩100M' : initialEquity > 0 ? `₩${fmtKrw(initialEquity)}` : '—', sub: initialIs100m ? 'qualification capital' : 'legacy / mismatch check' },
  ];

  const onMouseDown = (event: React.MouseEvent<HTMLDivElement>) => { const target = event.target as HTMLElement; if (target.closest('button,a,input,textarea,select')) return; const node = scrollRef.current; if (!node) return; dragRef.current = { active: true, y: event.clientY, top: node.scrollTop }; node.style.cursor = 'grabbing'; };
  const onMouseMove = (event: React.MouseEvent<HTMLDivElement>) => { const node = scrollRef.current; if (!node || !dragRef.current.active) return; node.scrollTop = dragRef.current.top - (event.clientY - dragRef.current.y); };
  const releaseDrag = () => { dragRef.current.active = false; if (scrollRef.current) scrollRef.current.style.cursor = 'grab'; };

  return <div ref={scrollRef} onMouseDown={onMouseDown} onMouseMove={onMouseMove} onMouseUp={releaseDrag} onMouseLeave={releaseDrag} className="h-full cursor-grab overflow-y-auto bg-[#05070A] px-4 pb-24 pt-4 md:px-6 lg:pb-8 xl:px-8">
    <div className="mx-auto max-w-[1560px]">
      <header className="mb-4 flex flex-wrap items-end justify-between gap-3 border-b border-white/[0.06] pb-4"><div><div className="font-mono text-[7px] uppercase tracking-[0.22em] text-[#43D9E6]">Black Oracle · live paper observability</div><h1 className="mt-1 text-2xl font-medium tracking-[-0.035em] text-[#EDF1F4]">ORACLE</h1><p className="mt-1 max-w-3xl text-[11px] leading-relaxed text-[#65707A]">무엇을 보고, 왜 거래하거나 기다리는지와 신규 진입이 왜 허용·축소·차단됐는지를 한 화면에서 표시합니다.</p></div><div className="flex items-center gap-2"><div className="hidden items-center gap-1 font-mono text-[7px] text-[#505B65] lg:flex"><GripVertical className="h-3 w-3" /> drag to scroll</div><button onClick={() => setCurrentView('strategies')} className="border border-white/[0.08] px-3 py-2 font-mono text-[7px] uppercase tracking-[0.12em] text-[#73808A]">Lab</button><button onClick={() => setCurrentView('log')} className="border border-white/[0.08] px-3 py-2 font-mono text-[7px] uppercase tracking-[0.12em] text-[#73808A]">Full log</button><button onClick={() => void load()} className="flex items-center gap-2 border border-[#43D9E6]/20 px-3 py-2 font-mono text-[7px] uppercase tracking-[0.12em] text-[#78C8D0]"><RefreshCw className={`h-3 w-3 ${loading ? 'animate-spin' : ''}`} /> refresh</button></div></header>

      {!initialIs100m && initialEquity > 0 && <div className="mb-4 border border-[#D2B36A]/25 bg-[#D2B36A]/[0.04] px-4 py-3 text-[10px] leading-relaxed text-[#BFA66B]">현재 연결된 checkpoint의 초기자본은 ₩{fmtKrw(initialEquity)}입니다. 화면의 ₩100M 표기를 강제로 맞추지 않고 실제 runtime 값을 표시합니다. 새 ₩100M qualification runtime으로 전환되면 이 경고가 사라집니다.</div>}

      <div className="mb-4 grid grid-cols-2 gap-px border border-white/[0.07] bg-white/[0.07] sm:grid-cols-4 xl:grid-cols-7">{statusCells.map((cell) => <div key={cell.label} className="min-w-0 bg-[#070B10] p-3.5"><Kicker>{cell.label}</Kicker><div className={`mt-2 truncate font-mono text-[11px] ${tone(cell.value)}`}>{cell.value}</div><div className="mt-1 truncate text-[8px] text-[#505B65]">{cell.sub}</div></div>)}</div>

      <div className="mb-4 grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
        <Card><div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-3"><div><Kicker>Portfolio equity</Kicker><div className="mt-1 text-[12px] text-[#D4DBE0]">실제 checkpoint 자본곡선</div></div><TrendingUp className="h-4 w-4 text-[#6EC9D1]" /></div><div className="grid grid-cols-2 gap-px bg-white/[0.05] sm:grid-cols-4"><Metric label="Initial" value={`₩${fmtKrw(initialEquity)}`} /><Metric label="Equity" value={`₩${fmtKrw(payload?.portfolio?.equity)}`} /><Metric label="Realized" value={`₩${fmtKrw(payload?.portfolio?.realizedPnl)}`} valueClass={Number(payload?.portfolio?.realizedPnl ?? 0) >= 0 ? 'text-[#77B9A5]' : 'text-[#D07D7D]'} /><Metric label="Unrealized" value={`₩${fmtKrw(totalUnrealized)}`} valueClass={totalUnrealized >= 0 ? 'text-[#77B9A5]' : 'text-[#D07D7D]'} /></div><div className="h-[270px] p-4">{equityData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={equityData}><CartesianGrid stroke="rgba(255,255,255,0.035)" vertical={false} /><XAxis dataKey="time" tick={{ fill: '#59656F', fontSize: 8 }} axisLine={false} tickLine={false} minTickGap={24} /><YAxis domain={['dataMin', 'dataMax']} tick={{ fill: '#59656F', fontSize: 8 }} axisLine={false} tickLine={false} tickFormatter={(value) => `${(Number(value) / 1_000_000).toFixed(1)}M`} width={42} /><Tooltip contentStyle={{ background: '#080D12', border: '1px solid rgba(255,255,255,0.10)', fontSize: 10 }} formatter={(value: any) => [`₩${fmtKrw(Number(value))}`, 'Equity']} /><ReferenceLine y={initialEquity} stroke="rgba(255,255,255,0.18)" strokeDasharray="4 4" /><Area type="monotone" dataKey="equity" stroke="#43D9E6" fill="#43D9E6" fillOpacity={0.08} strokeWidth={1.5} /></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-[10px] text-[#56616B]">Equity curve가 쌓이면 여기에 표시됩니다.</div>}</div></Card>

        <Card><div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-3"><div><Kicker>New Entry Safety</Kicker><div className="mt-1 text-[12px] text-[#D4DBE0]">동적 SL/TP + 주문 전 안전검사</div></div><ShieldCheck className="h-4 w-4 text-[#6EC9D1]" /></div><div className="p-4"><div className={`font-mono text-xl ${tone(safetyState)}`}>{safetyState}</div><div className="mt-1 text-[10px] text-[#65717A]">{safetyDecision ? `${safetyDecision.market} · Oracle ${safetyDecision.oracleTradeScore ?? '—'}` : '현재 신규 진입 후보가 Risk 단계까지 오지 않았습니다.'}</div>{safetyDecision && <div className="mt-4 grid grid-cols-3 gap-2"><div className="border border-white/[0.06] p-2"><Kicker>SL</Kicker><div className="mt-1 font-mono text-[9px] text-[#C8D0D5]">{safetyDecision.tradeMap?.stopLossPrice ? fmtKrw(safetyDecision.tradeMap.stopLossPrice) : '—'}</div></div><div className="border border-white/[0.06] p-2"><Kicker>TP1</Kicker><div className="mt-1 font-mono text-[9px] text-[#C8D0D5]">{safetyDecision.tradeMap?.takeProfit1Price ? fmtKrw(safetyDecision.tradeMap.takeProfit1Price) : '—'}</div></div><div className="border border-white/[0.06] p-2"><Kicker>TP2</Kicker><div className="mt-1 font-mono text-[9px] text-[#C8D0D5]">{safetyDecision.tradeMap?.takeProfit2Price ? fmtKrw(safetyDecision.tradeMap.takeProfit2Price) : '—'}</div></div></div>}
          <div className="mt-4 space-y-4"><div><div className="flex justify-between text-[9px] text-[#77828B]"><span>Daily loss</span><span>{pct(-dailyLoss)} · throttle −1% / emergency −3%</span></div><Progress value={(dailyLoss / 0.03) * 100} /></div><div><div className="flex justify-between text-[9px] text-[#77828B]"><span>Total drawdown</span><span>{pct(drawdown)} / 5% emergency</span></div><Progress value={(drawdown / 0.05) * 100} /></div></div>
          <div className="mt-4 border-t border-white/[0.06] pt-3"><Kicker>Current reason</Kicker><div className="mt-2 text-[10px] leading-relaxed text-[#A6B0B7]">{safetyDecision?.riskReasons?.[0] || safetyDecision?.primaryReason || (safetyState === 'IDLE' ? '신규 진입 후보가 없어 Safety를 평가하지 않았습니다.' : 'Safety checks passed.')}</div></div>
        </div></Card>
      </div>

      <div className="mb-4 grid gap-4 xl:grid-cols-2">
        <Card><div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-3"><div><Kicker>Evidence flow</Kicker><div className="mt-1 text-[12px] text-[#D4DBE0]">NARS → Eligible → Decision attached</div></div><Database className="h-4 w-4 text-[#65717B]" /></div><div className="h-[230px] p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={evidenceChart}><CartesianGrid stroke="rgba(255,255,255,0.035)" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#66717B', fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fill: '#59656F', fontSize: 8 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: '#080D12', border: '1px solid rgba(255,255,255,0.10)', fontSize: 10 }} /><Bar dataKey="value" fill="#43D9E6" /></BarChart></ResponsiveContainer></div><div className="border-t border-white/[0.05] px-4 py-3 text-[9px] leading-relaxed text-[#626D76]">`0 eligible`은 열린 포지션이 0이라는 뜻이 아닙니다. 현재 거래에 사용할 수 있는 만료되지 않은 외부 Evidence가 없다는 뜻입니다.</div></Card>

        <Card><div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-3"><div><Kicker>Shadow Council</Kicker><div className="mt-1 text-[12px] text-[#D4DBE0]">실행권 없는 독립 검토</div></div><Bot className="h-4 w-4 text-[#6EC9D1]" /></div>{latestCouncil ? <div className="p-4"><div className="flex items-center justify-between"><div className={`font-mono text-lg ${tone(latestCouncil.verdict)}`}>{latestCouncil.verdict}</div><div className="font-mono text-[7px] uppercase text-[#56616B]">authority NO</div></div><div className="mt-3 grid grid-cols-4 gap-2 text-center font-mono text-[8px]"><div className="border border-white/[0.05] p-2"><div className="text-[#77B9A5]">{latestCouncil.approveCount}</div><div className="mt-1 text-[#56616B]">APPROVE</div></div><div className="border border-white/[0.05] p-2"><div className="text-[#C7AA71]">{latestCouncil.cautionCount}</div><div className="mt-1 text-[#56616B]">CAUTION</div></div><div className="border border-white/[0.05] p-2"><div className="text-[#D07D7D]">{latestCouncil.rejectCount}</div><div className="mt-1 text-[#56616B]">REJECT</div></div><div className="border border-white/[0.05] p-2"><div className="text-[#9AA5AE]">{latestCouncil.abstainCount}</div><div className="mt-1 text-[#56616B]">ABSTAIN</div></div></div><div className="mt-3 text-[10px] leading-relaxed text-[#8D98A1]">{latestCouncil.summary}</div></div> : <div className="p-8 text-center text-[10px] text-[#56616B]">최근 Council snapshot이 없습니다.</div>}</Card>
      </div>

      <div className="mb-4 grid gap-4 xl:grid-cols-[1fr_1fr]">
        <Card><div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-3"><div><Kicker>Open positions</Kicker><div className="mt-1 text-[12px] text-[#D4DBE0]">보호가격은 시장상태에 따라 상향 조정</div></div><WalletCards className="h-4 w-4 text-[#65717B]" /></div><div className="divide-y divide-white/[0.045]">{positions.map((position) => { const ret = position.entryPrice > 0 ? (position.markPrice - position.entryPrice) / position.entryPrice : 0; return <button key={position.market} onClick={() => setCurrentView('log')} className="grid w-full gap-2 px-4 py-3 text-left sm:grid-cols-[100px_80px_1fr] sm:items-center"><div className="font-mono text-[9px] text-[#E1E6EA]">{position.market}</div><div className={`font-mono text-[9px] ${ret >= 0 ? 'text-[#77B9A5]' : 'text-[#D07D7D]'}`}>{pct(ret)}</div><div className="flex flex-wrap gap-x-3 gap-y-1 font-mono text-[7px] text-[#59656F]"><span>SL {position.stopLossPrice == null ? '—' : fmtKrw(position.stopLossPrice)}</span><span>TP1 {position.takeProfit1Price == null ? '—' : fmtKrw(position.takeProfit1Price)}</span><span>TP2 {position.takeProfit2Price == null ? '—' : fmtKrw(position.takeProfit2Price)}</span><span>rev {position.protectionRevision ?? 0}</span></div></button>; })}{!positions.length && <div className="px-4 py-8 text-center text-[10px] text-[#58636D]">현재 열린 Paper 포지션이 없습니다.</div>}</div></Card>

        <Card><div className="border-b border-white/[0.06] px-4 py-3"><Kicker>Decision tape</Kicker><div className="mt-1 text-[12px] text-[#D4DBE0]">Risk까지 평가된 후보를 포함한 최신 의사결정</div></div><div className="divide-y divide-white/[0.045]">{decisions.slice(0, 8).map((decision) => <button key={`${decision.market}-${decision.timestamp}`} onClick={() => setSelected(decision)} className="grid w-full grid-cols-[90px_1fr_auto] items-center gap-3 px-4 py-3 text-left hover:bg-white/[0.015]"><div><div className="font-mono text-[9px] text-[#DDE3E7]">{decision.market}</div><div className="mt-1 font-mono text-[7px] text-[#4F5A64]">{ago(decision.timestamp)}</div></div><div><div className="text-[9px] text-[#A0ABB3]">{decision.primaryReason || decision.reasons?.[0] || 'No reason'}</div><div className="mt-1 font-mono text-[7px] text-[#58636D]">{decision.regime || '—'} · score {decision.oracleTradeScore ?? '—'}</div></div><div className={`font-mono text-[8px] ${tone(decision.riskDisposition || decision.decision)}`}>{decision.riskDisposition === 'NOT_EVALUATED' ? decision.decision : decision.riskDisposition}</div></button>)}{!decisions.length && <div className="px-4 py-8 text-center text-[10px] text-[#58636D]">최근 decision이 없습니다.</div>}</div></Card>
      </div>

      <div className="grid gap-4 xl:grid-cols-2"><Card><div className="border-b border-white/[0.06] px-4 py-3"><Kicker>Eligible evidence</Kicker><div className="mt-1 text-[12px] text-[#D4DBE0]">현재 유효한 외부 근거</div></div><div className="divide-y divide-white/[0.045]">{evidence.slice(0, 8).map((item) => <div key={item.id} className="px-4 py-3"><div className="flex items-center justify-between gap-3"><div className="text-[10px] text-[#C6CED3]">{item.title}</div><div className={`font-mono text-[7px] ${tone(item.direction)}`}>{item.direction}</div></div><div className="mt-1 font-mono text-[7px] text-[#53606A]">{item.market} · {item.evidence_grade || 'UNGRADED'} · {item.source_type || 'source'}</div></div>)}{!evidence.length && <div className="px-4 py-8 text-center text-[10px] text-[#58636D]">현재 eligible external Evidence가 없습니다.</div>}</div></Card><Card><div className="border-b border-white/[0.06] px-4 py-3"><Kicker>Recent outcomes</Kicker><div className="mt-1 text-[12px] text-[#D4DBE0]">닫힌 Paper 거래</div></div><div className="divide-y divide-white/[0.045]">{trades.slice(0, 8).map((trade) => <div key={trade.id} className="grid grid-cols-[90px_1fr_auto] items-center gap-3 px-4 py-3"><div className="font-mono text-[9px] text-[#DDE3E7]">{trade.market}</div><div className="font-mono text-[7px] text-[#53606A]">{trade.exitReason || trade.strategyVersion || 'closed'}</div><div className={`font-mono text-[9px] ${trade.netPnl >= 0 ? 'text-[#77B9A5]' : 'text-[#D07D7D]'}`}>{trade.netPnl >= 0 ? '+' : ''}₩{fmtKrw(trade.netPnl)} · {pct(trade.returnPct)}</div></div>)}{!trades.length && <div className="px-4 py-8 text-center text-[10px] text-[#58636D]">아직 닫힌 거래가 없습니다.</div>}</div></Card></div>
    </div>

    {selected && <div className="fixed inset-0 z-50 flex items-end justify-end bg-black/55 p-3 md:p-5"><div className="max-h-[88vh] w-full max-w-xl overflow-y-auto border border-white/[0.10] bg-[#080C11] shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-white/[0.07] bg-[#080C11] px-4 py-3"><div><Kicker>Decision detail</Kicker><div className="mt-1 font-mono text-[12px] text-[#E0E6E9]">{selected.market} · {selected.decision}</div></div><button onClick={() => setSelected(null)} className="p-2 text-[#6B7680]"><X className="h-4 w-4" /></button></div><div className="space-y-4 p-4"><div className="grid grid-cols-3 gap-2"><Metric label="Oracle" value={String(selected.oracleTradeScore ?? '—')} /><Metric label="Strategy" value={selected.strategyDisposition || '—'} /><Metric label="Safety" value={selected.riskDisposition || 'NOT EVALUATED'} valueClass={tone(selected.riskDisposition)} /></div><div><Kicker>Primary reason</Kicker><div className="mt-2 text-[11px] leading-relaxed text-[#AAB4BB]">{selected.primaryReason || selected.reasons?.[0] || '—'}</div></div><div><Kicker>Safety reasons</Kicker><div className="mt-2 space-y-1 text-[10px] leading-relaxed text-[#8F9AA3]">{(selected.riskReasons?.length ? selected.riskReasons : ['Risk was not evaluated for this decision.']).map((reason, index) => <div key={index}>• {reason}</div>)}</div></div><div><Kicker>Dynamic trade map</Kicker><div className="mt-2 grid grid-cols-3 gap-2 font-mono text-[9px] text-[#B7C0C6]"><div className="border border-white/[0.06] p-2">SL<br />{selected.tradeMap?.stopLossPrice ? fmtKrw(selected.tradeMap.stopLossPrice) : '—'}</div><div className="border border-white/[0.06] p-2">TP1<br />{selected.tradeMap?.takeProfit1Price ? fmtKrw(selected.tradeMap.takeProfit1Price) : '—'}</div><div className="border border-white/[0.06] p-2">TP2<br />{selected.tradeMap?.takeProfit2Price ? fmtKrw(selected.tradeMap.takeProfit2Price) : '—'}</div></div></div></div></div></div>}
  </div>;
};
