import type { PlanTier } from '../../src/commercial/creditContracts';

export const ENTITLEMENT_POLICY_VERSION = 1 as const;

export const ENTITLEMENTS = [
  'VIEW_BASIC_MARKET',
  'VIEW_REPORT_PREVIEW',
  'VIEW_FULL_DEBATE',
  'VIEW_LEAD_CONCLUSION',
  'VIEW_FULL_REPORT',
  'VIEW_EVIDENCE_DETAIL',
  'VIEW_FORECAST',
  'VIEW_REPORT_HISTORY_COMPARE',
  'USE_ALERTS',
  'USE_ADVANCED_ALERTS',
  'ASK_SIMPLE_AI_QUESTION',
  'COMPARE_ASSETS',
  'REFRESH_REPORT',
  'INVITE_EXPERT',
  'REQUEST_RED_TEAM',
  'RERUN_DEBATE',
  'REQUEST_NEW_REPORT',
  'REQUEST_DEEP_RESEARCH',
  'USE_SCHEDULED_RESEARCH',
  'USE_RESEARCH_TRIGGER_ALERT',
] as const;

export type Entitlement = (typeof ENTITLEMENTS)[number];

const PLAN_ENTITLEMENTS: Readonly<Record<PlanTier, readonly Entitlement[]>> = {
  CORE: [
    'VIEW_BASIC_MARKET',
    'VIEW_REPORT_PREVIEW',
  ],
  PLUS: [
    'VIEW_BASIC_MARKET',
    'VIEW_REPORT_PREVIEW',
    'VIEW_FULL_DEBATE',
    'VIEW_LEAD_CONCLUSION',
    'USE_ALERTS',
    'ASK_SIMPLE_AI_QUESTION',
  ],
  PRO: [
    'VIEW_BASIC_MARKET',
    'VIEW_REPORT_PREVIEW',
    'VIEW_FULL_DEBATE',
    'VIEW_LEAD_CONCLUSION',
    'VIEW_FULL_REPORT',
    'VIEW_EVIDENCE_DETAIL',
    'VIEW_FORECAST',
    'VIEW_REPORT_HISTORY_COMPARE',
    'USE_ALERTS',
    'USE_ADVANCED_ALERTS',
    'ASK_SIMPLE_AI_QUESTION',
    'COMPARE_ASSETS',
    'REFRESH_REPORT',
    'INVITE_EXPERT',
    'REQUEST_RED_TEAM',
  ],
  MAX: [
    'VIEW_BASIC_MARKET',
    'VIEW_REPORT_PREVIEW',
    'VIEW_FULL_DEBATE',
    'VIEW_LEAD_CONCLUSION',
    'VIEW_FULL_REPORT',
    'VIEW_EVIDENCE_DETAIL',
    'VIEW_FORECAST',
    'VIEW_REPORT_HISTORY_COMPARE',
    'USE_ALERTS',
    'USE_ADVANCED_ALERTS',
    'ASK_SIMPLE_AI_QUESTION',
    'COMPARE_ASSETS',
    'REFRESH_REPORT',
    'INVITE_EXPERT',
    'REQUEST_RED_TEAM',
    'RERUN_DEBATE',
    'REQUEST_NEW_REPORT',
    'REQUEST_DEEP_RESEARCH',
    'USE_SCHEDULED_RESEARCH',
    'USE_RESEARCH_TRIGGER_ALERT',
  ],
  ENTERPRISE: ENTITLEMENTS,
};

export const hasEntitlement = (plan: PlanTier, entitlement: Entitlement) =>
  PLAN_ENTITLEMENTS[plan].includes(entitlement);

export const entitlementsForPlan = (plan: PlanTier) => [...PLAN_ENTITLEMENTS[plan]];
